/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nura;

/**
 *
 * @author Admin
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        All = new javax.swing.JPanel();
        Zavtrak = new javax.swing.JPanel();
        Obed = new javax.swing.JPanel();
        Ujin = new javax.swing.JPanel();
        First = new javax.swing.JPanel();
        Second = new javax.swing.JPanel();
        Third = new javax.swing.JPanel();
        Des = new javax.swing.JPanel();
        other = new javax.swing.JTabbedPane();
        east = new javax.swing.JPanel();
        rus = new javax.swing.JPanel();
        fr = new javax.swing.JPanel();
        ital = new javax.swing.JPanel();
        my = new javax.swing.JPanel();
        like = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Есть у меня тут пара рецептов!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(249, 246, 222));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(253, 230, 182));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(500, 400));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(400, 200));

        javax.swing.GroupLayout AllLayout = new javax.swing.GroupLayout(All);
        All.setLayout(AllLayout);
        AllLayout.setHorizontalGroup(
            AllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        AllLayout.setVerticalGroup(
            AllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Все рецепты", All);

        javax.swing.GroupLayout ZavtrakLayout = new javax.swing.GroupLayout(Zavtrak);
        Zavtrak.setLayout(ZavtrakLayout);
        ZavtrakLayout.setHorizontalGroup(
            ZavtrakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        ZavtrakLayout.setVerticalGroup(
            ZavtrakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Завтрак", Zavtrak);

        javax.swing.GroupLayout ObedLayout = new javax.swing.GroupLayout(Obed);
        Obed.setLayout(ObedLayout);
        ObedLayout.setHorizontalGroup(
            ObedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        ObedLayout.setVerticalGroup(
            ObedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Обед", Obed);

        javax.swing.GroupLayout UjinLayout = new javax.swing.GroupLayout(Ujin);
        Ujin.setLayout(UjinLayout);
        UjinLayout.setHorizontalGroup(
            UjinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        UjinLayout.setVerticalGroup(
            UjinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ужин", Ujin);

        javax.swing.GroupLayout FirstLayout = new javax.swing.GroupLayout(First);
        First.setLayout(FirstLayout);
        FirstLayout.setHorizontalGroup(
            FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        FirstLayout.setVerticalGroup(
            FirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Первые блюда", First);

        javax.swing.GroupLayout SecondLayout = new javax.swing.GroupLayout(Second);
        Second.setLayout(SecondLayout);
        SecondLayout.setHorizontalGroup(
            SecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        SecondLayout.setVerticalGroup(
            SecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Вторые блюда", Second);

        javax.swing.GroupLayout ThirdLayout = new javax.swing.GroupLayout(Third);
        Third.setLayout(ThirdLayout);
        ThirdLayout.setHorizontalGroup(
            ThirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        ThirdLayout.setVerticalGroup(
            ThirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Салаты и закуски", Third);

        javax.swing.GroupLayout DesLayout = new javax.swing.GroupLayout(Des);
        Des.setLayout(DesLayout);
        DesLayout.setHorizontalGroup(
            DesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        DesLayout.setVerticalGroup(
            DesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Десерты и выпечка", Des);

        other.setBackground(new java.awt.Color(253, 230, 182));

        javax.swing.GroupLayout eastLayout = new javax.swing.GroupLayout(east);
        east.setLayout(eastLayout);
        eastLayout.setHorizontalGroup(
            eastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        eastLayout.setVerticalGroup(
            eastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        other.addTab("Восточная", east);

        javax.swing.GroupLayout rusLayout = new javax.swing.GroupLayout(rus);
        rus.setLayout(rusLayout);
        rusLayout.setHorizontalGroup(
            rusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        rusLayout.setVerticalGroup(
            rusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        other.addTab("Русская", rus);

        javax.swing.GroupLayout frLayout = new javax.swing.GroupLayout(fr);
        fr.setLayout(frLayout);
        frLayout.setHorizontalGroup(
            frLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        frLayout.setVerticalGroup(
            frLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        other.addTab("Французская", fr);

        javax.swing.GroupLayout italLayout = new javax.swing.GroupLayout(ital);
        ital.setLayout(italLayout);
        italLayout.setHorizontalGroup(
            italLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        italLayout.setVerticalGroup(
            italLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        other.addTab("Итальянская", ital);

        jTabbedPane1.addTab("Кухни разных народов", other);

        javax.swing.GroupLayout myLayout = new javax.swing.GroupLayout(my);
        my.setLayout(myLayout);
        myLayout.setHorizontalGroup(
            myLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        myLayout.setVerticalGroup(
            myLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Добавленное ", my);

        javax.swing.GroupLayout likeLayout = new javax.swing.GroupLayout(like);
        like.setLayout(likeLayout);
        likeLayout.setHorizontalGroup(
            likeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        likeLayout.setVerticalGroup(
            likeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Избранное", like);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 410, 260));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/меню.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 450));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/есть.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 240, 190));

        jButton2.setBackground(new java.awt.Color(249, 246, 222));
        jButton2.setForeground(new java.awt.Color(51, 30, 24));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/добавить_1.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 141, -1));

        jButton1.setBackground(new java.awt.Color(253, 230, 182));
        jButton1.setForeground(new java.awt.Color(51, 30, 24));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Выход_1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 130, -1));

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new AddFrame(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ExitFrame(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel All;
    private javax.swing.JPanel Des;
    private javax.swing.JPanel First;
    private javax.swing.JPanel Obed;
    private javax.swing.JPanel Second;
    private javax.swing.JPanel Third;
    private javax.swing.JPanel Ujin;
    private javax.swing.JPanel Zavtrak;
    private javax.swing.JPanel east;
    private javax.swing.JPanel fr;
    private javax.swing.JPanel ital;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel like;
    private javax.swing.JPanel my;
    private javax.swing.JTabbedPane other;
    private javax.swing.JPanel rus;
    // End of variables declaration//GEN-END:variables
}
